import { tableListTree } from "./tableTree";
import { decodeHTMLStrict } from "entities";
import { orderFootnoteTree } from "./footnoteOrder";
import { remarkMark } from "remark-mark-highlight";
import { remarkShorthand } from "../markdownShorthand";
import { editableBlockTree } from "./blockTree";
import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import remarkFrontmatter from "remark-frontmatter";
import type { Node as ProseNode } from "@milkdown/kit/prose/model";
import { sourceChange } from "../markdownSession";

export interface SourceNode {
  type: string; value?: string; children?: SourceNode[];
  position?: { start: { offset?: number }; end: { offset?: number } };
}
const syntax = unified().use(remarkParse).use(remarkGfm, { singleTilde: false }).use(remarkMark).use(remarkShorthand).use(remarkMath).use(remarkFrontmatter, ["yaml", "toml"]);
export function sourceTree(source: string): SourceNode { return syntax.parse(source) as SourceNode; }
function editingTree(source: string): SourceNode { const tree = sourceTree(source); editableBlockTree(tree, source); tableListTree(tree, source); orderFootnoteTree(tree); return tree; }
const protectedTypes = new Set(["html", "definition", "linkReference", "imageReference", "yaml", "toml"]);
export function protectedBlock(node: SourceNode): boolean {
  if (node.type === "paragraph" && /^\[(?:toc|\[toc\])\]$/i.test(node.children?.map(n => n.value ?? "").join("") ?? "")) return true;
  return protectedTypes.has(node.type) || !!node.children?.some(protectedBlock);
}
export function range(node: SourceNode): [number, number] {
  return [node.position?.start.offset ?? 0, node.position?.end.offset ?? 0];
}
export function protectedTree(tree: SourceNode, source: string, mdx: boolean) {
  if (mdx && source) tree.children = [{ type: "deditorRaw", value: source }];
  else tree.children = tree.children?.map(node => protectedBlock(node)
    ? { type: "deditorRaw", value: source.slice(...range(node)), position: node.position } : node);
}
function children(node: ProseNode) { const result: ProseNode[] = []; node.forEach(n => result.push(n)); return result; }
// Inline links carry their destination in the block. Unresolved brackets in
// text may instead become reference links when parsed with document definitions.
function needsDocumentContext(node: SourceNode): boolean {
  return ["definition", "linkReference", "imageReference", "footnoteDefinition", "footnoteReference", "html"].includes(node.type)
    || node.type === "text" && !!node.value?.includes("[")
    || !!node.children?.some(needsDocumentContext);
}
// Heading anchors are generated by Milkdown after parsing, including during undo.
// They must never cause untouched headings and their original gaps to be serialized.
function sameSourceMarkup(a: ProseNode, b: ProseNode): boolean {
  return a.type.name === "heading" && b.type === a.type
    ? a.type.create({ ...a.attrs, id: b.attrs.id }, a.content, a.marks).sameMarkup(b)
    : a.sameMarkup(b);
}
function sameSourceNode(a: ProseNode, b: ProseNode): boolean {
  if (a.eq(b)) return true;
  if (!sameSourceMarkup(a, b) || a.childCount !== b.childCount) return false;
  return a.isText ? a.text === b.text : children(a).every((n, i) => sameSourceNode(n, b.child(i)));
}
function sameStructure(a: ProseNode, b: ProseNode): boolean {
  if (!sameSourceMarkup(a, b) || a.childCount !== b.childCount) return false;
  return a.isText || children(a).every((n, i) => sameStructure(n, b.child(i)));
}
/** Text-only edits use original token offsets, retaining list markers, escapes and CRLF. */
function patchText(raw: string, ast: SourceNode, before: ProseNode, after: ProseNode): string | null {
  if (!sameStructure(before, after)) return null;
  const leaves: SourceNode[] = [];
  const walk = (n: SourceNode) => { if (["text", "inlineCode", "code", "math"].includes(n.type)) leaves.push(n); else n.children?.forEach(walk); };
  walk(ast);
  const oldText: string[] = [], newText: string[] = [];
  before.descendants(n => { if (n.isText) oldText.push(n.text!); });
  after.descendants(n => { if (n.isText) newText.push(n.text!); });
  if (leaves.length !== oldText.length || oldText.length !== newText.length) return null;
  const base = range(ast)[0];
  const edits: { from: number; to: number; insert: string }[] = [];
  for (let i = 0; i < leaves.length; i++) {
    if (oldText[i] === newText[i]) continue;
    const leaf = leaves[i], [start, end] = range(leaf);
    const token = raw.slice(start - base, end - base);
    const value = leaf.value ?? "";
    if (value !== oldText[i]) return null;
    // Never guess through escapes/entities, indentation, or ambiguous fence content.
    let inner = token === value ? 0 : -1;
    if (leaf.type === "inlineCode") inner = token.indexOf(value);
    if (leaf.type === "code" || leaf.type === "math") inner = token.indexOf(value, token.indexOf("\n") + 1);
    if (inner < 0 || token.slice(inner, inner + value.length) !== value) return null;
    const diff = sourceChange(value, newText[i]);
    edits.push({ from: start - base + inner + diff.from, to: start - base + inner + diff.from + diff.removed.length, insert: diff.inserted });
  }
  for (const e of edits.reverse()) raw = raw.slice(0, e.from) + e.insert + raw.slice(e.to);
  return raw;
}

function patchTasks(raw: string, ast: SourceNode, before: ProseNode, after: ProseNode): string | null {
  if (before.textContent !== after.textContent) return null;
  const oldItems: ProseNode[] = [], newItems: ProseNode[] = [], items: SourceNode[] = [];
  before.descendants(n => { if (n.type.name === "list_item") oldItems.push(n); });
  after.descendants(n => { if (n.type.name === "list_item") newItems.push(n); });
  const walk = (n: SourceNode) => { if (n.type === "listItem") items.push(n); n.children?.forEach(walk); }; walk(ast);
  if (!oldItems.length || oldItems.length !== newItems.length || items.length !== oldItems.length) return null;
  const base = range(ast)[0];
  for (let i = items.length - 1; i >= 0; i--) {
    if (oldItems[i].attrs.checked === newItems[i].attrs.checked) continue;
    const start = range(items[i])[0] - base;
    const match = raw.slice(start).match(/^(?:[-+*]|\d+[.)])\s+\[([ xX])\]/);
    if (!match || typeof newItems[i].attrs.checked !== "boolean") return null;
    const at = start + match[0].length - 2;
    raw = raw.slice(0, at) + (newItems[i].attrs.checked ? "x" : " ") + raw.slice(at + 1);
  }
  return raw;
}

export interface MarkdownDocumentSnapshot { doc: ProseNode; ast: SourceNode[] }

/** Keeps original source ranges; only the transaction's changed blocks are serialized. */
export class MarkdownDocument {
  source: string;
  doc: ProseNode;
  private ast: SourceNode[] = [];
  private positions = new WeakMap<ProseNode, { ast: SourceNode; start: number; ranges: { from: number; to: number; pos: number; end: number }[] }>();
  constructor(source: string, private parse: (source: string) => ProseNode, private serialize: (doc: ProseNode) => string, private mdx = false, initialDoc?: ProseNode) {
    this.source = source; this.doc = initialDoc ?? parse(source); this.index();
  }
  private index() {
    this.ast = this.mdx && this.source ? [{ type: "deditorRaw", value: this.source, position: { start: { offset: 0 }, end: { offset: this.source.length } } }] : editingTree(this.source).children ?? [];
    if (this.ast.length > this.doc.childCount) throw new Error("Markdown source ranges do not match the editable document");
    // Crepe may append an empty paragraph for a terminal table/code/atom.
    while (this.ast.length < this.doc.childCount) this.ast.push({ type: "paragraph", position: { start: { offset: this.source.length }, end: { offset: this.source.length } } });
  }
  snapshot(): MarkdownDocumentSnapshot { return { doc: this.doc, ast: this.ast }; }
  restore(source: string, snapshot: MarkdownDocumentSnapshot) {
    this.source = source;
    this.doc = snapshot.doc.type.schema === this.doc.type.schema ? snapshot.doc : this.doc.type.schema.nodeFromJSON(snapshot.doc.toJSON());
    this.ast = snapshot.ast;
    return this.doc;
  }
  project(next: ProseNode) { this.doc = next; }
  /** Reparse only a changed top-level prose block when its source boundaries remain stable. */
  reparseInlineBlock(position: number) {
    const resolved = this.doc.resolve(position), index = resolved.index(0), node = this.doc.child(index), ast = this.ast[index];
    if (!ast || !["paragraph", "heading", "blockquote", "table"].includes(node.type.name) || ast.type !== node.type.name) return null;
    const [start, end] = range(ast), raw = this.source.slice(start, end);
    // Reparse the enclosing block, including multiline prose, a quote, or a
    // table. A paste that creates siblings or definitions must still reparse
    // the whole document because it can change neighboring reference meaning.
    const fragment = editingTree(raw).children ?? [];
    const hasDefinition = (n: SourceNode): boolean => ["definition", "footnoteDefinition"].includes(n.type) || !!n.children?.some(hasDefinition);
    if (fragment.length !== 1 || fragment[0].type !== ast.type || hasDefinition(fragment[0])) return null;
    const definitions = this.ast.filter(n => ["definition", "footnoteDefinition"].includes(n.type)).map(n => this.source.slice(...range(n))).join("\n\n");
    const parsed = this.parse(raw + (definitions ? "\n\n" + definitions : ""));
    if (!parsed.firstChild || parsed.firstChild.type !== node.type) return null;
    return { from: resolved.before(1), to: resolved.after(1), node: parsed.firstChild };
  }
  editInline(from: number, length: number, raw: string, next: ProseNode) {
    const end = from + length, delta = raw.length - length;
    const multiline = /[\r\n]/.test(this.source.slice(from, end));
    const shift = (n: SourceNode): SourceNode => ({ ...n, position: n.position ? {
      start: { offset: (n.position.start.offset ?? 0) >= end ? (n.position.start.offset ?? 0) + delta : n.position.start.offset },
      end: { offset: (n.position.end.offset ?? 0) >= end ? (n.position.end.offset ?? 0) + delta : n.position.end.offset },
    } : undefined, children: n.children?.map(shift) });
    this.source = this.source.slice(0, from) + raw + this.source.slice(end);
    this.ast = this.ast.map(shift);
    // An inline edit without line breaks cannot consume a neighboring block.
    // Re-index only its enclosing block unless reference resolution or a block
    // boundary/type change requires whole-document context.
    const blockIndex = this.ast.findIndex(n => { const [start, stop] = range(n); return start <= from && from + raw.length <= stop; });
    const block = this.ast[blockIndex];
    const contextual = (n: SourceNode): boolean => ["definition", "footnoteDefinition", "linkReference", "imageReference", "footnoteReference"].includes(n.type) || !!n.children?.some(contextual);
    let local = false;
    if (block && !multiline && !/[\r\n\[]/.test(raw) && !contextual(block)) {
      const [start, stop] = range(block);
      const parsed = editingTree(this.source.slice(start, stop)).children ?? [];
      if (parsed.length === 1 && parsed[0].type === block.type && !contextual(parsed[0])) {
        const offset = (n: SourceNode): SourceNode => ({ ...n, position: n.position ? { start: { offset: start + (n.position.start.offset ?? 0) }, end: { offset: start + (n.position.end.offset ?? 0) } } : undefined, children: n.children?.map(offset) });
        this.ast[blockIndex] = offset(parsed[0]); local = true;
      }
    }
    if (!local) {
      const parsed = editingTree(this.source).children ?? [];
      if (parsed.length === this.ast.length) this.ast = parsed;
    }
    this.doc = next;
  }
  inlineAt(position: number) {
    const offset = this.sourceOffset(position);
    const supported = new Set(["strong", "emphasis", "delete", "link", "linkReference", "inlineCode", "mark", "subscript", "superscript"]);
    let token: SourceNode | undefined;
    const walk = (n: SourceNode) => {
      const [from, to] = range(n);
      if (offset < from || offset > to || token) return;
      if (supported.has(n.type)) { token = n; return; }
      n.children?.forEach(walk);
    };
    this.ast.forEach(walk);
    if (!token) return null;
    const leaves: SourceNode[] = [];
    const texts = (n: SourceNode) => { if (n.type === "text" || n.type === "inlineCode") leaves.push(n); else n.children?.forEach(texts); };
    texts(token); if (!leaves.length) return null;
    const [sourceFrom, sourceTo] = range(token), raw = this.source.slice(sourceFrom, sourceTo);
    const start = range(leaves[0])[0] + (leaves[0].type === "inlineCode" ? this.source.slice(...range(leaves[0])).indexOf(leaves[0].value ?? "") : 0);
    const end = range(leaves.at(-1)!)[1] - (leaves.at(-1)!.type === "inlineCode" ? this.source.slice(...range(leaves.at(-1)!)).length - this.source.slice(...range(leaves.at(-1)!)).indexOf(leaves.at(-1)!.value ?? "") - (leaves.at(-1)!.value?.length ?? 0) : 0);
    let from: number | undefined, to: number | undefined;
    this.doc.forEach((node, offset, index) => {
      if (position < offset || position > offset + node.nodeSize) return;
      const ranges = this.textRanges(node, index, offset);
      const first = ranges.find(r => start >= r.from && start < r.to);
      const last = ranges.find(r => end > r.from && end <= r.to);
      if (first) from = first.pos + Math.min(start - first.from, first.end - first.pos);
      if (last) to = end === last.to ? last.end : last.pos + Math.min(end - last.from, last.end - last.pos);
    });
    if (from === undefined || to === undefined) return null;
    // Source offsets are approximate at non-text positions (for example before
    // a hard break in a list). They may point into an earlier inline token.
    // Only expand a token that actually contains the caret in the rendered doc.
    if (to <= from || position < from || position > to ||
        !this.doc.resolve(from).sameParent(this.doc.resolve(to))) return null;
    return { from, to, sourceFrom, raw };
  }
  reset(source: string) {
    const change = sourceChange(this.source, source), end = change.from + change.removed.length;
    // Plain, single-line edits inside one existing block have no effect on
    // neighboring Markdown boundaries. Contextual references/HTML and line edits
    // deliberately use the complete parser because their context can be global.
    if (source !== this.source && !this.mdx && !/[\r\n]/.test(change.removed + change.inserted)) {
      const index = this.ast.findIndex(node => { const [a, b] = range(node); return a <= change.from && end <= b; });
      const previous = this.ast[index];
      // Fences can stay the same node type while consuming later blocks if
      // their closing delimiter changes. Keep code, math and containers global.
      if (previous && ["paragraph", "heading", "table"].includes(previous.type)) {
        const [start, stop] = range(previous), delta = change.inserted.length - change.removed.length;
        const raw = this.source.slice(start, change.from) + change.inserted + this.source.slice(end, stop);
        if (!raw.includes("<") && !needsDocumentContext(previous)) {
          const ast = editingTree(raw).children ?? [];
          const parsed = ast.length === 1 && ast[0].type === previous.type && !needsDocumentContext(ast[0]) ? this.parse(raw) : null;
          if (parsed?.childCount === 1 && parsed.firstChild!.type === this.doc.child(index).type) {
            const offset = (node: SourceNode, local: boolean): SourceNode => ({ ...node,
              position: node.position ? {
                start: { offset: local ? start + (node.position.start.offset ?? 0) : (node.position.start.offset ?? 0) + ((node.position.start.offset ?? 0) >= stop ? delta : 0) },
                end: { offset: local ? start + (node.position.end.offset ?? 0) : (node.position.end.offset ?? 0) + ((node.position.end.offset ?? 0) >= stop ? delta : 0) },
              } : undefined, children: node.children?.map(child => offset(child, local)),
            });
            const blocks = children(this.doc); blocks[index] = parsed.firstChild!;
            this.source = source; this.doc = this.doc.type.create(this.doc.attrs, blocks, this.doc.marks);
            this.ast = this.ast.map((node, at) => offset(at === index ? ast[0] : node, at === index));
            return this.doc;
          }
        }
      }
    }
    this.source = source; this.doc = this.parse(source); this.index(); return this.doc;
  }
  apply(next: ProseNode): string {
    if (sameSourceNode(next, this.doc)) { this.doc = next; return this.source; }
    if (this.doc.content.content.some(node => node.type.name === "footnote_definition") || next.content.content.some(node => node.type.name === "footnote_definition")) return this.applyBlockProjection(next);
    const before = children(this.doc), after = children(next);
    let first = 0;
    while (first < before.length && first < after.length && sameSourceNode(before[first], after[first])) first++;
    let oldEnd = before.length, newEnd = after.length;
    while (oldEnd > first && newEnd > first && sameSourceNode(before[oldEnd - 1], after[newEnd - 1])) { oldEnd--; newEnd--; }
    // A replace-all or multi-block format transaction can change distant blocks.
    // Reuse the disjoint projection so untouched blocks and their gaps stay exact.
    if (before.length === after.length && newEnd - first > 1) return this.applyBlockProjection(next);
    const from = first < this.ast.length ? range(this.ast[first])[0] : this.source.length;
    const to = oldEnd > first ? range(this.ast[oldEnd - 1])[1] : from;
    const eol = this.source.includes("\r\n") ? "\r\n" : "\n";
    const changed = after.slice(first, newEnd);
    const definitions = this.ast.filter(node => ["definition", "footnoteDefinition"].includes(node.type)).map(node => this.source.slice(...range(node))).join("\n");
    const serializeBlock = (block: ProseNode) => block.type.name === "deditor_raw" ? block.textContent : this.serialize(next.type.create(null, block)).replace(/\n$/, "").replace(/\r?\n/g, eol);
    let parts = changed.map(serializeBlock);
    if (oldEnd - first === 1 && changed.length === 1 && changed[0].type.name !== "deditor_raw") {
      const raw = this.source.slice(from, to);
      const patched = patchText(raw, this.ast[first], before[first], changed[0]) ?? patchTasks(raw, this.ast[first], before[first], changed[0]);
      if (patched !== null) {
        // A literal '*' or a newline must not turn into unintended Markdown
        // when saved. Only retain token spelling if it reparses equivalently.
        const parsed = this.parse(patched + (definitions ? "\n\n" + definitions : ""));
        const reparsed = definitions && parsed.firstChild ? parsed.type.create(null, parsed.firstChild) : parsed;
        const expected = this.serialize(next.type.create(null, changed[0]));
        if (this.serialize(reparsed) === expected) parts = [patched];
      }
    }
    let replacement = parts.join(eol + eol), leading = "", trailing = "";
    if (oldEnd === first && changed.length) {
      if (from > 0 && (!replacement || !this.source.slice(0, from).endsWith(eol + eol))) leading = eol + eol;
      if (from < this.source.length) trailing = eol + eol;
    }
    replacement = leading + replacement + trailing;
    const delta = replacement.length - (to - from);
    const shifted = (node: SourceNode, offset: number): SourceNode => ({ ...node,
      position: node.position ? { start: { offset: (node.position.start.offset ?? 0) + offset }, end: { offset: (node.position.end.offset ?? 0) + offset } } : undefined,
      children: node.children?.map(child => shifted(child, offset)),
    });
    let cursor = from + leading.length;
    const spans = parts.map((part, index) => {
      const parsed = (editingTree(part + (definitions ? "\n\n" + definitions : "")).children ?? []).filter(node => range(node)[0] < part.length);
      const ast = changed[index].type.name !== "deditor_raw" && parsed.length === 1
        ? shifted(parsed[0], cursor)
        : { type: "deditorRaw", position: { start: { offset: cursor }, end: { offset: cursor + part.length } } };
      cursor += part.length + eol.length * 2;
      return ast;
    });
    this.ast = [...this.ast.slice(0, first), ...spans, ...this.ast.slice(oldEnd).map(node => shifted(node, delta))];
    this.source = this.source.slice(0, from) + replacement + this.source.slice(to);
    this.doc = next;
    return this.source;
  }
  /** Patch disjoint source blocks independently, including reordered footnote footers. */
  private applyBlockProjection(next: ProseNode): string {
    const before = children(this.doc), after = children(next), eol = this.source.includes("\r\n") ? "\r\n" : "\n";
    type Edit = {from:number;to:number;insert:string};
    const edits: Edit[] = [], assigned = new Map<ProseNode,{ast:SourceNode;edit?:Edit;relative?:number}>();
    const definitions = this.ast.filter(node => node.type === "footnoteDefinition" || node.type === "definition").map(node=>this.source.slice(...range(node))).join("\n\n");
    const serialize = (node:ProseNode) => node.type.name === "deditor_raw" ? node.textContent : this.serialize(next.type.create(null,node)).replace(/\n$/,"").replace(/\r?\n/g,eol);
    const offsetTree = (node:SourceNode, amount:number):SourceNode => ({...node,position:node.position?{start:{offset:(node.position.start.offset??0)+amount},end:{offset:(node.position.end.offset??0)+amount}}:undefined,children:node.children?.map(child=>offsetTree(child,amount))});
    // The usual keystroke changes one block. Avoid building a complete projection
    // map for thousands of unaffected paragraphs/tables just because a footer exists.
    if (before.length === after.length) {
      let changed = -1, multiple = false;
      for (let index = 0; index < before.length; index++) if (!sameSourceNode(before[index], after[index])) {
        if (changed >= 0) { multiple = true; break; }
        changed = index;
      }
      if (!multiple && changed >= 0 && this.ast[changed]) {
        const ast = this.ast[changed], node = after[changed], [from, to] = range(ast);
        let raw = serialize(node);
        const patch = patchText(this.source.slice(from,to), ast, before[changed], node) ?? patchTasks(this.source.slice(from,to), ast, before[changed], node);
        if (patch !== null) {
          const parsed = this.parse(patch + (definitions ? "\n\n" + definitions : ""));
          const candidate = children(parsed).find(child => child.type === node.type && (node.type.name !== "footnote_definition" || child.attrs.identifier === node.attrs.identifier));
          if (candidate && this.serialize(parsed.type.create(null,candidate)) === this.serialize(next.type.create(null,node))) raw = patch;
        }
        const parsed = (editingTree(raw + (definitions ? "\n\n" + definitions : "")).children ?? []).filter(node => range(node)[0] < raw.length);
        const replacement = parsed.length === 1 ? parsed[0] : {type:"deditorRaw",position:{start:{offset:0},end:{offset:raw.length}}};
        const delta = raw.length - (to - from);
        this.ast = this.ast.map((entry, index) => index === changed ? offsetTree(replacement, from) : delta && range(entry)[0] >= to ? offsetTree(entry, delta) : entry);
        this.source = this.source.slice(0,from) + raw + this.source.slice(to);
        this.doc = next; return this.source;
      }
    }
    const replace = (oldIndex:number|undefined, node:ProseNode|undefined, insertion:number) => {
      const old = oldIndex === undefined ? undefined : before[oldIndex], ast = oldIndex === undefined ? undefined : this.ast[oldIndex];
      if(old && node && ast && sameSourceNode(old,node)){assigned.set(node,{ast});return;}
      const [from,to] = ast ? range(ast) : [insertion,insertion];
      let raw = node ? serialize(node) : "";
      if(ast && old && node && node.type.name !== "deditor_raw") {
        const patch = patchText(this.source.slice(from,to),ast,old,node) ?? patchTasks(this.source.slice(from,to),ast,old,node);
        if(patch !== null) {
          const parsed=this.parse(patch + (definitions ? "\n\n"+definitions : ""));
          const candidate=children(parsed).find(child=>child.type===node.type && (node.type.name!=="footnote_definition" || child.attrs.identifier===node.attrs.identifier));
          if(candidate && this.serialize(parsed.type.create(null,candidate))===this.serialize(next.type.create(null,node)))raw=patch;
        }
      }
      const priorInsertion = edits.some(edit => edit.from === from && edit.to === from && edit.insert);
      const leading = !ast && (priorInsertion || from>0 && !this.source.slice(0,from).endsWith(eol+eol)) ? eol+eol : "";
      const trailing = !ast && from<this.source.length ? eol+eol : "";
      const edit={from,to,insert:leading+raw+trailing};edits.push(edit);
      if(node) {
        const parsed=(editingTree(raw + (definitions ? "\n\n"+definitions : "")).children??[]).filter(node => range(node)[0] < raw.length);
        const local=parsed.length===1 ? parsed[0] : {type:"deditorRaw",position:{start:{offset:0},end:{offset:raw.length}}};
        assigned.set(node,{ast:local,edit,relative:leading.length});
      }
    };
    const oldBody=before.flatMap((node,index)=>node.type.name === "footnote_definition"?[]:[index]);
    const newBody=after.filter(node=>node.type.name !== "footnote_definition");
    let first=0;while(first<oldBody.length && first<newBody.length && sameSourceNode(before[oldBody[first]],newBody[first])) {replace(oldBody[first],newBody[first],0);first++;}
    let oldEnd=oldBody.length,newEnd=newBody.length;
    while(oldEnd>first && newEnd>first && sameSourceNode(before[oldBody[oldEnd-1]],newBody[newEnd-1])) {replace(oldBody[oldEnd-1],newBody[newEnd-1],0);oldEnd--;newEnd--;}
    if(oldEnd-first===newEnd-first) {
      for(let i=first;i<oldEnd;i++)replace(oldBody[i],newBody[i],0);
    } else {
      const at=first<oldBody.length ? range(this.ast[oldBody[first]])[0] : this.source.length;
      const newNodes=newBody.slice(first,newEnd), raw=newNodes.map(serialize).join(eol+eol);
      // Remove only body spans: definitions between them retain their exact original bytes.
      for(let i=first;i<oldEnd;i++)replace(oldBody[i],undefined,0);
      if(raw) {
        const leading=at>0&&!this.source.slice(0,at).endsWith(eol+eol)?eol+eol:"";
        const edit={from:at,to:at,insert:leading+raw+(at<this.source.length?eol+eol:"")};edits.push(edit);
        let offset=leading.length;
        newNodes.forEach(node=>{const part=serialize(node), parsed=(editingTree(part + (definitions ? "\n\n"+definitions : "")).children??[]).filter(node => range(node)[0] < part.length);assigned.set(node,{ast:parsed[0]??{type:"deditorRaw",position:{start:{offset:0},end:{offset:part.length}}},edit,relative:offset});offset+=part.length+2*eol.length;});
      }
    }
    const unused = before.flatMap((node,index)=>node.type.name === "footnote_definition"?[index]:[]);
    for(const node of after.filter(node=>node.type.name === "footnote_definition")) {
      const index=unused.findIndex(index=>before[index].attrs.identifier===node.attrs.identifier);
      replace(index<0?undefined:unused.splice(index,1)[0],node,this.source.length);
    }
    unused.forEach(index=>replace(index,undefined,0));
    // Stable tie ordering puts an insertion before a deletion at the same source boundary.
    edits.sort((a,b)=>a.from-b.from || a.to-b.to);
    const shift = (position:number, own?:Edit) => {
      const ownIndex = own ? edits.indexOf(own) : edits.length;
      return edits.reduce((delta, edit, index) => {
        if (edit === own || edit.to > position) return delta;
        if (edit.from === position && index >= ownIndex) return delta;
        return delta + edit.insert.length - (edit.to - edit.from);
      }, 0);
    };
    this.ast=after.map(node=>{
      const entry=assigned.get(node);if(!entry)throw new Error("Missing Markdown footer source mapping");
      if(entry.edit)return offsetTree(entry.ast,entry.edit.from+shift(entry.edit.from,entry.edit)+(entry.relative??0));
      return offsetTree(entry.ast,shift(range(entry.ast)[0]));
    });
    for(const edit of [...edits].reverse())this.source=this.source.slice(0,edit.from)+edit.insert+this.source.slice(edit.to);
    this.doc=next;return this.source;
  }
  private textRanges(node: ProseNode, index: number, start: number) {
    const ast = this.ast[index];
    if (!ast) return [];
    const cached = this.positions.get(node);
    if (cached?.ast === ast && cached.start === start) return cached.ranges;
    const leaves: SourceNode[] = [], prose: { text: string; pos: number }[] = [];
    const emptySource: number[] = [], emptyProse: number[] = [];
    const walk = (n: SourceNode) => {
      if (["paragraph", "listItem"].includes(n.type) && !n.children?.length) emptySource.push(range(n)[1]);
      if (["text", "inlineCode", "code", "math", "break"].includes(n.type)) leaves.push(n);
      else if (n.type === "html" && /^<br\s*\/?>$/i.test(n.value ?? "")) leaves.push({ ...n, type: "break" });
      else n.children?.forEach(walk);
    };
    walk(ast);
    node.descendants((child, pos) => {
      if (child.type.name === "paragraph" && !child.content.size) emptyProse.push(start + pos + 2);
      if (child.type.name === "deditor_inline_source") {
        const from = Number(child.attrs.sourceFrom), to = from + child.textContent.length;
        const first = leaves.findIndex(leaf => range(leaf)[0] >= from && range(leaf)[1] <= to);
        if (first >= 0) {
          let count = 0; while (first + count < leaves.length && range(leaves[first + count])[1] <= to) count++;
          leaves.splice(first, count, { type: "text", value: child.textContent, position: { start: { offset: from }, end: { offset: to } } });
        }
        prose.push({ text: child.textContent, pos: start + pos + 2 }); return false;
      }
      if (child.isText) prose.push({ text: child.text!, pos: start + pos + 1 });
      else if (child.type.name === "hardbreak") prose.push({ text: "\n", pos: start + pos + 1 });
    });
    const ranges: { from: number; to: number; pos: number; end: number }[] = [];
    // Marks split/merge ProseMirror text nodes independently of Markdown leaves.
    // Align the actual text stream instead of requiring equal leaf counts.
    const value = (leaf: SourceNode) => leaf.type === "break" ? "\n" : leaf.value ?? "";
    if (leaves.map(value).join("") === prose.map(run => run.text).join("")) {
      let run = 0, inner = 0;
      for (const leaf of leaves) {
        const text = value(leaf), [from, to] = range(leaf), raw = this.source.slice(from, to);
        const at = raw === text ? 0 : leaf.type === "text" ? -1 : raw.indexOf(text);
        const leafRanges: typeof ranges = [];
        let valid = true;
        for (let i = 0, rawAt = at < 0 ? 0 : at; i < text.length; i++) {
          while (run < prose.length && inner >= prose[run].text.length) { inner -= prose[run].text.length; run++; }
          if (!prose[run]) break;
          const pos = prose[run].pos + inner++;
          let length = 1, decoded = raw[rawAt];
          if (leaf.type === "break") { rawAt = 0; length = raw.length; decoded = "\n"; }
          else if (at < 0) {
            const rest = raw.slice(rawAt), entity = rest.match(/^&(?:#x[\da-f]+|#\d+|[a-z][\da-z]*);/i)?.[0];
            if (entity) { decoded = decodeHTMLStrict(entity); length = entity.length; }
            else if (/^\\[!"#$%&'()*+,\-./:;<=>?@[\\\]^_`{|}~]/.test(rest)) { decoded = rest[1]; length = 2; }
            else if (rest.startsWith("\r\n")) { decoded = "\n"; length = 2; }
          }
          if (decoded && decoded.length > 1 && text.slice(i, i + decoded.length) === decoded) {
            const width = decoded.length;
            // Character references can decode to a surrogate pair (or multiple
            // code points). Keep their complete source spelling as one span.
            if (inner + width - 1 <= prose[run].text.length) {
              leafRanges.push({ from: from + rawAt, to: from + rawAt + length, pos, end: pos + width });
            } else valid = false;
            inner += width - 1; i += width - 1;
          } else if (decoded === text[i]) {
            const previous = leafRanges.at(-1), stop = from + rawAt + length;
            if (length === 1 && previous && previous.to === from + rawAt && previous.end === pos && previous.to - previous.from === previous.end - previous.pos) { previous.to = stop; previous.end++; }
            else leafRanges.push({ from: from + rawAt, to: stop, pos, end: pos + 1 });
          } else valid = false;
          rawAt += length;
        }
        // Unsupported normalization must not leave partially guessed offsets.
        if (valid) ranges.push(...leafRanges);
      }
    }
    if (emptySource.length === emptyProse.length) emptySource.forEach((from, i) => ranges.push({ from, to: from, pos: emptyProse[i], end: emptyProse[i] }));
    ranges.sort((a, b) => a.pos - b.pos);
    this.positions.set(node, { ast, start, ranges });
    return ranges;
  }
  sourceOffset(position: number) {
    let found = this.source.length;
    this.doc.forEach((node, offset, index) => {
      if (position >= offset && position <= offset + node.nodeSize && this.ast[index]) {
        const [from, to] = range(this.ast[index]);
        found = Math.min(to, from + Math.max(0, position - offset - 1));
        const ranges = this.textRanges(node, index, offset);
        const segment = ranges.find(r => position === r.pos) ?? ranges.find(r => position > r.pos && position <= r.end);
        if (segment) found = position === segment.end ? segment.to : segment.from + Math.min(position - segment.pos, segment.to - segment.from);
        else if (ranges.length) {
          const nearest = ranges.reduce((best, r) => Math.min(Math.abs(position-r.pos), Math.abs(position-r.end)) < Math.min(Math.abs(position-best.pos), Math.abs(position-best.end)) ? r : best);
          found = position < nearest.pos ? nearest.from : nearest.to;
        }
      }
    });
    return found;
  }
  positionAtSource(offset: number) {
    let pos = 1, closestEnd = -1, matched = false;
    this.doc.forEach((node, start, index) => {
      const [from, to] = this.ast[index] ? range(this.ast[index]) : [0, 0];
      if (!matched && offset > to && to > closestEnd) {closestEnd=to;pos=start+node.nodeSize-1;}
      if (offset >= from && offset <= to) {
        matched=true;
        pos = start + Math.min(node.nodeSize - 1, Math.max(1, offset - from + 1));
        const segment = this.textRanges(node, index, start).find(r => offset >= r.from && offset <= r.to);
        if (segment) pos = offset === segment.to ? segment.end : segment.pos + Math.min(offset - segment.from, segment.end - segment.pos);
      }
    });
    return Math.min(this.doc.content.size, Math.max(0, pos));
  }
}
